### PR TITLE
[1.x] Enable single_line_empty_body fixer

### PR DESCRIPTION
**Pull request by Jubeki**
In many of my applications I have an empty constructor body, with only private or public attributes directly defined in the constructor parameter list. This results in an ugly code formatting in many cases.

This PR proposes to enable the `single_line_empty_body` fixer in the laravel preset.

Given the following file:

```php
<?php

new class
{
    public function __construct(
        private string $name = '',
    ) {
    }

    public function function2() {}

    public function function3()
    {
        //
    }

    public function function4(
        string $name
    )
    {
        //
    }

    public function function5(
        string $name
    ) {
        //
    }

    public function function6() {
        // should still be fixed by the braces fixer
    }
};
```

The following changes would occur:

```diff
@@ -4,8 +4,7 @@
 {
     public function __construct(
         private string $name = '',
-    ) {
-    }
+    ) {}

     public function function2() {}

@@ -16,8 +15,7 @@

     public function function4(
         string $name
-    )
-    {
+    ) {
         //
     }

@@ -27,7 +25,8 @@
         //
     }

-    public function function6() {
+    public function function6()
+    {
         // should still be fixed by the braces fixer
     }
 };
```

### CODE REVIEW

**Comment by lupinitylabs** [comment]
Frankly, I would appreciate if changes like these would not simply become a default for all Pint configurations that are based on that preset. I can see how this could be a strong preference for some people, but it's just that - a preference, not a necessary fix.

One needs to keep in mind that this results in an awful lot of changes to code in reviews from one pint version to the next, and it's quite an annoyance, and that on a global scale, for a lot of repositories at once.

**Comment by driesvints** [comment]
Hey @lupinitylabs, I think you summarised that quite well, thank you. The Laravel preset is indeed opinionated and if you don't wish to be on par with (future) Laravel coding standards then the Laravel preset isn't for you and you might want to roll your own.

**Comment by ju5t** [comment]
@driesvints I think changes to presets should not be in a patch version. It should be a minor version as it feels like a new feature. If preset changes get released in minor versions you can pin Pint to the minor version and not miss out on bug fixes.

**Comment by ju5t** [comment]
Ah sorry, it didn't pop up when I searched for it. Thanks for the explanation.

**Comment by driesvints** [comment]
@ju5t no worries 👍

**Pull request merged**
