### PR TITLE
[1.x] Supports PHP 8.4

### PR DESCRIPTION
**Pull request by crynobone**
* [x] `illuminate/support`: https://github.com/laravel/framework/pull/53612
* [ ] `friendsofphp/php-cs-fixer`: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/milestone/173`
* [ ] `laravel-zero/foundation`: Sync changes from `illuminate/foundation` via https://github.com/laravel-zero/foundation/pull/104
* [x] `nunomaduro/termwind`
* [x] `nunomaduro/collision`

`composer.json` and `composer.lock` was updated using:

```bash
composer update --patch-only --bump-after-update
```

### CODE REVIEW

**Comment by Jubeki** [comment]
Hey @crynobone there are deprecations in the PHP 8.4 Unit Tests when running `vendor/bin/pest`.

This is probably due to using Laravel Zero v10 and illuminate/view v10  instead of v11.

**Comment by mokhosh** [comment]
@crynobone this should be fine to merge?

**Comment by Jubeki** [comment]
@mokhosh I think this is pending the next release of illuminate/xxx 10.48.5 (so probably Tuesday)

**Comment by Jubeki** [comment]
@crynobone I am not sure if Laravel Pint can fully support PHP 8.4 for now.

PHP-CS-Fixer has not full PHP 8.4 support. A corresponding, PR is WIP: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8300

You currently can only run PHP-CS-Fixer with the following env flag enabled:
```bash
PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix
```

(I think Pint runs, even though this flag is not set, I did not test this.)

**Comment by Wirone** [comment]
Yes, you can run Fixer on any PHP version using `PHP_CS_FIXER_IGNORE_ENV =1`, but it's **_not recommended_** for such a widely used tool as Pint and having in mind how big 8.4 is in terms of syntax-related features. I recommend observing mentioned PR and [this milestone](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/milestone/173), where I started to collect issues found on 8.4. More issues will be added there likely, I just did not have time to cover more 8.4 features yet.

**Comment by crynobone** [comment]
Replaced with #321 and #322

**Pull request closed without merging**
