### PR TITLE
[0.x] Adds support for specifying custom rules in `pint.json`

### PR DESCRIPTION
**Pull request by lukeraymonddowning**
Hello there!

It would be nice in Pint if you were able to reference custom fixers for rules that aren't built into the package by default. This PR adds that functionality by allowing a developer to register a `fixers` array in their `pint.json` file.

```json
{
    "fixers": [
        "App\\Fixers\\MyFixer"
    ]
}
```

The `fixers` array should contain FQCNs of `FixerInterface` classes. Pint will look these up when building the config, and automatically set them to `true` in the rules array.

A user may override `rules` if they wish by specifying the fixer name in the `rules` config:

```json
{
    "fixers": [
        "App\\Fixers\\MyFixer"
    ],
    "rules": {
        "App/My_Fixer": {
            "some_custom_config": true
        }
    }
}
```

This allows for passing more specific arguments if the custom rule accepts them.

### CODE REVIEW

**Comment by Jubeki** [comment]
I think your custom fixers will not be loaded, because Pint is standalone and should not be loading your composer autoload file. Or am I wrong there?

**Comment by lukeraymonddowning** [comment]
Lol @Jubeki good point 😁 Need to think of a way around that. Any suggestions?

**Comment by lukeraymonddowning** [comment]
Converting to draft until I solve the Elephant in the room

**Comment by nunomaduro** [comment]
@lukeraymonddowning You may be able to "require" the file. Yet, for now, we plan allow custom rules. Maybe in the future!

**Pull request closed without merging**
