### PR TITLE
Fix the tax version extraction.

### PR DESCRIPTION
**Pull request by lucasmichot**
This PR fixes the tax version extraction.

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks!

**Comment by lucasmichot** [comment]
(tag) sorry for the typo

**Comment by driesvints** [comment]
@lucasmichot we're still getting failures on this build: https://github.com/laravel/pint/actions/runs/2740662270

But it seems to have worked anyway: https://github.com/laravel/pint/actions/runs/2740662276

Why are the failures happening? https://github.com/laravel/pint/actions

Screenshot 2022-07-26 at 18 08 04

**Comment by lucasmichot** [comment]
Hi hard to say @driesvints, I have created a PR to hopefully mitigate this issue : https://github.com/laravel/pint/pull/92

**Pull request merged**
