### PR TITLE
Fix actions versions for PHAR deployment job.

### PR DESCRIPTION
**Pull request by lucasmichot**
This PR fixes the actions versions for the PHAR deployment job.

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks

**Comment by driesvints** [comment]
@lucasmichot actions is still failing: https://github.com/laravel/pint/actions/runs/2569574304

**Comment by lucasmichot** [comment]
Thanks @driesvints 👁️ 
I will have a look at this

**Comment by lucasmichot** [comment]
cf. https://github.com/laravel/pint/pull/57

**Pull request merged**
